# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class BusinessLocationDTO(BaseModel):
    # The country in which the business is located or business is performed. The country code must follow ISO 3166 standards in alpha-2 format (two-letter code).
    country_code: typing.Optional[str] = Field(None, alias='countryCode')

    # The postal code associated with the business location. Cannot be blank.
    postal_code: typing.Optional[str] = Field(None, alias='postalCode')
    class Config:
        arbitrary_types_allowed = True
