# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MetricValidationSummaryDTO(BaseModel):
    # The symbol name of the metric. For example, \"employeeCount\".
    symbol_name: typing.Optional[str] = Field(None, alias='symbolName')

    # An identifiable name that is displayed within Visier. For example, \"Headcount\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The current value of the metric expressed as an integer.
    value: typing.Optional[typing.Union[int, float]] = Field(None, alias='value')
    class Config:
        arbitrary_types_allowed = True
