# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ModuleSettingsDTO(BaseModel):
    # If true, the module cannot be assigned to tenants.
    unavailable_for_assignment: typing.Optional[bool] = Field(None, alias='unavailableForAssignment')

    # An instruction message in the module selection dialog. This can be a note for administrators such as \"Don't assign this module\" or \"Assign Module B instead\".
    special_handling_instruction: typing.Optional[str] = Field(None, alias='specialHandlingInstruction')

    # The language of the module. For example, a module that is in English will have the locale \"en\".
    locale: typing.Optional[str] = Field(None, alias='locale')
    class Config:
        arbitrary_types_allowed = True
