# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TenantStatusAPIDTO(BaseModel):
    # The unique identifier for the analytic tenant.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # Whether the tenant is enabled or disabled.
    status: typing.Optional[str] = Field(None, alias='status')

    # The identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
    tenant_display_name: typing.Optional[str] = Field(None, alias='tenantDisplayName')

    # If true, the tenant is an administrating tenant.
    can_administer_other_tenants: typing.Optional[bool] = Field(None, alias='canAdministerOtherTenants')
    class Config:
        arbitrary_types_allowed = True
