# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_tenant_management_python_sdk.pydantic.module_settings_dto import ModuleSettingsDTO

class TenantModuleDTO(BaseModel):
    # An identifiable name that is displayed within Visier. For example, \"TALENT\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The symbol name of the module. For example, \"Talent_Management\".
    symbol_name: typing.Optional[str] = Field(None, alias='symbolName')

    # The settings associated with the module.
    module_settings: typing.Optional[ModuleSettingsDTO] = Field(None, alias='moduleSettings')
    class Config:
        arbitrary_types_allowed = True
