# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_tenant_management_python_sdk.pydantic.metric_validation_summary_dto import MetricValidationSummaryDTO

class TenantPreviewEntriesSummaryDTO(BaseModel):
    # The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The data version ID.
    data_version: typing.Optional[str] = Field(None, alias='dataVersion')

    # The date that the data version was created.
    data_version_date: typing.Optional[str] = Field(None, alias='dataVersionDate')

    # A list of metrics and their values.
    metrics: typing.Optional[typing.List[MetricValidationSummaryDTO]] = Field(None, alias='metrics')
    class Config:
        arbitrary_types_allowed = True
