# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_tenant_management_python_sdk.pydantic.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.pydantic.tenant_detail_apidto_embeddable_domains import TenantDetailAPIDTOEmbeddableDomains
from visier_tenant_management_python_sdk.pydantic.tenant_detail_apidto_sso_instance_issuers import TenantDetailAPIDTOSsoInstanceIssuers
from visier_tenant_management_python_sdk.pydantic.tenant_module_dto import TenantModuleDTO

class TenantDetailAPIDTO(BaseModel):
    # The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # An identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
    tenant_display_name: typing.Optional[str] = Field(None, alias='tenantDisplayName')

    # Whether the tenant is enabled or disabled.
    status: typing.Optional[str] = Field(None, alias='status')

    # The date that the tenant was created.
    provision_date: typing.Optional[str] = Field(None, alias='provisionDate')

    # The data version ID that the tenant is using.
    current_data_version: typing.Optional[str] = Field(None, alias='currentDataVersion')

    # The date that the data version was published to production.
    data_version_date: typing.Optional[str] = Field(None, alias='dataVersionDate')

    # The modules assigned to the analytic tenant.
    modules: typing.Optional[typing.List[TenantModuleDTO]] = Field(None, alias='modules')

    # The 6-digit NAICS code for the industry to which the analytic tenant belongs.
    industry_code: typing.Optional[int] = Field(None, alias='industryCode')

    # If true, the tenant is an administrating tenant.
    can_administer_other_tenants: typing.Optional[bool] = Field(None, alias='canAdministerOtherTenants')

    embeddable_domains: typing.Optional[TenantDetailAPIDTOEmbeddableDomains] = Field(None, alias='embeddableDomains')

    # A set of key-value pairs that represent different customizable properties for the analytic tenant.
    custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = Field(None, alias='customProperties')

    sso_instance_issuers: typing.Optional[TenantDetailAPIDTOSsoInstanceIssuers] = Field(None, alias='ssoInstanceIssuers')

    # The name of the administrating tenant used in Visier URLs.
    vanity_url_name: typing.Optional[str] = Field(None, alias='vanityUrlName')
    class Config:
        arbitrary_types_allowed = True
