# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_tenant_management_python_sdk
from visier_tenant_management_python_sdk.model.update_tenant_model_sso_instance_issuers import UpdateTenantModelSsoInstanceIssuers
from visier_tenant_management_python_sdk import configuration


class TestUpdateTenantModelSsoInstanceIssuers(unittest.TestCase):
    """UpdateTenantModelSsoInstanceIssuers unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
