# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_tenant_management_python_sdk
from visier_tenant_management_python_sdk.model.tenant_management_api_update_response_dto_purchased_modules import TenantManagementAPIUpdateResponseDTOPurchasedModules
from visier_tenant_management_python_sdk import configuration


class TestTenantManagementAPIUpdateResponseDTOPurchasedModules(unittest.TestCase):
    """TenantManagementAPIUpdateResponseDTOPurchasedModules unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
