# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_tenant_management_python_sdk
from visier_tenant_management_python_sdk.model.tenant_management_api_update_request_dto_sso_instance_issuers import TenantManagementAPIUpdateRequestDTOSsoInstanceIssuers
from visier_tenant_management_python_sdk import configuration


class TestTenantManagementAPIUpdateRequestDTOSsoInstanceIssuers(unittest.TestCase):
    """TenantManagementAPIUpdateRequestDTOSsoInstanceIssuers unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
