# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_tenant_management_python_sdk import schemas  # noqa: F401


class HomeAnalysisByUserGroupDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            userGroupId = schemas.StrSchema
            homeAnalysisId = schemas.StrSchema
            __annotations__ = {
                "userGroupId": userGroupId,
                "homeAnalysisId": homeAnalysisId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userGroupId"]) -> MetaOapg.properties.userGroupId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["homeAnalysisId"]) -> MetaOapg.properties.homeAnalysisId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["userGroupId", "homeAnalysisId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userGroupId"]) -> typing.Union[MetaOapg.properties.userGroupId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["homeAnalysisId"]) -> typing.Union[MetaOapg.properties.homeAnalysisId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["userGroupId", "homeAnalysisId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        userGroupId: typing.Union[MetaOapg.properties.userGroupId, str, schemas.Unset] = schemas.unset,
        homeAnalysisId: typing.Union[MetaOapg.properties.homeAnalysisId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'HomeAnalysisByUserGroupDTO':
        return super().__new__(
            cls,
            *args,
            userGroupId=userGroupId,
            homeAnalysisId=homeAnalysisId,
            _configuration=_configuration,
            **kwargs,
        )
