# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_tenant_management_python_sdk import schemas  # noqa: F401


class TenantProvisionAPIDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            tenantCode = schemas.StrSchema
            tenantDisplayName = schemas.StrSchema
        
            @staticmethod
            def purchasedModules() -> typing.Type['TenantProvisionAPIDTOPurchasedModules']:
                return TenantProvisionAPIDTOPurchasedModules
            industryCode = schemas.IntSchema
        
            @staticmethod
            def embeddableDomains() -> typing.Type['TenantProvisionAPIDTOEmbeddableDomains']:
                return TenantProvisionAPIDTOEmbeddableDomains
            
            
            class customProperties(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CustomTenantPropertyDTO']:
                        return CustomTenantPropertyDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['CustomTenantPropertyDTO'], typing.List['CustomTenantPropertyDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'customProperties':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CustomTenantPropertyDTO':
                    return super().__getitem__(i)
        
            @staticmethod
            def ssoInstanceIssuers() -> typing.Type['TenantProvisionAPIDTOSsoInstanceIssuers']:
                return TenantProvisionAPIDTOSsoInstanceIssuers
            __annotations__ = {
                "tenantCode": tenantCode,
                "tenantDisplayName": tenantDisplayName,
                "purchasedModules": purchasedModules,
                "industryCode": industryCode,
                "embeddableDomains": embeddableDomains,
                "customProperties": customProperties,
                "ssoInstanceIssuers": ssoInstanceIssuers,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenantCode"]) -> MetaOapg.properties.tenantCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenantDisplayName"]) -> MetaOapg.properties.tenantDisplayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purchasedModules"]) -> 'TenantProvisionAPIDTOPurchasedModules': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["industryCode"]) -> MetaOapg.properties.industryCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embeddableDomains"]) -> 'TenantProvisionAPIDTOEmbeddableDomains': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customProperties"]) -> MetaOapg.properties.customProperties: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ssoInstanceIssuers"]) -> 'TenantProvisionAPIDTOSsoInstanceIssuers': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tenantCode", "tenantDisplayName", "purchasedModules", "industryCode", "embeddableDomains", "customProperties", "ssoInstanceIssuers", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenantCode"]) -> typing.Union[MetaOapg.properties.tenantCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenantDisplayName"]) -> typing.Union[MetaOapg.properties.tenantDisplayName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purchasedModules"]) -> typing.Union['TenantProvisionAPIDTOPurchasedModules', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["industryCode"]) -> typing.Union[MetaOapg.properties.industryCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embeddableDomains"]) -> typing.Union['TenantProvisionAPIDTOEmbeddableDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customProperties"]) -> typing.Union[MetaOapg.properties.customProperties, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ssoInstanceIssuers"]) -> typing.Union['TenantProvisionAPIDTOSsoInstanceIssuers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tenantCode", "tenantDisplayName", "purchasedModules", "industryCode", "embeddableDomains", "customProperties", "ssoInstanceIssuers", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tenantCode: typing.Union[MetaOapg.properties.tenantCode, str, schemas.Unset] = schemas.unset,
        tenantDisplayName: typing.Union[MetaOapg.properties.tenantDisplayName, str, schemas.Unset] = schemas.unset,
        purchasedModules: typing.Union['TenantProvisionAPIDTOPurchasedModules', schemas.Unset] = schemas.unset,
        industryCode: typing.Union[MetaOapg.properties.industryCode, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        embeddableDomains: typing.Union['TenantProvisionAPIDTOEmbeddableDomains', schemas.Unset] = schemas.unset,
        customProperties: typing.Union[MetaOapg.properties.customProperties, list, tuple, schemas.Unset] = schemas.unset,
        ssoInstanceIssuers: typing.Union['TenantProvisionAPIDTOSsoInstanceIssuers', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TenantProvisionAPIDTO':
        return super().__new__(
            cls,
            *args,
            tenantCode=tenantCode,
            tenantDisplayName=tenantDisplayName,
            purchasedModules=purchasedModules,
            industryCode=industryCode,
            embeddableDomains=embeddableDomains,
            customProperties=customProperties,
            ssoInstanceIssuers=ssoInstanceIssuers,
            _configuration=_configuration,
            **kwargs,
        )

from visier_tenant_management_python_sdk.model.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_embeddable_domains import TenantProvisionAPIDTOEmbeddableDomains
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_purchased_modules import TenantProvisionAPIDTOPurchasedModules
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_sso_instance_issuers import TenantProvisionAPIDTOSsoInstanceIssuers
