# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_tenant_management_python_sdk import schemas  # noqa: F401


class TenantDetailAPIDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            tenantCode = schemas.StrSchema
            tenantDisplayName = schemas.StrSchema
            status = schemas.StrSchema
            provisionDate = schemas.StrSchema
            currentDataVersion = schemas.StrSchema
            dataVersionDate = schemas.StrSchema
            
            
            class modules(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TenantModuleDTO']:
                        return TenantModuleDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TenantModuleDTO'], typing.List['TenantModuleDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'modules':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TenantModuleDTO':
                    return super().__getitem__(i)
            industryCode = schemas.IntSchema
            canAdministerOtherTenants = schemas.BoolSchema
        
            @staticmethod
            def embeddableDomains() -> typing.Type['TenantDetailAPIDTOEmbeddableDomains']:
                return TenantDetailAPIDTOEmbeddableDomains
            
            
            class customProperties(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CustomTenantPropertyDTO']:
                        return CustomTenantPropertyDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['CustomTenantPropertyDTO'], typing.List['CustomTenantPropertyDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'customProperties':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CustomTenantPropertyDTO':
                    return super().__getitem__(i)
        
            @staticmethod
            def ssoInstanceIssuers() -> typing.Type['TenantDetailAPIDTOSsoInstanceIssuers']:
                return TenantDetailAPIDTOSsoInstanceIssuers
            vanityUrlName = schemas.StrSchema
            __annotations__ = {
                "tenantCode": tenantCode,
                "tenantDisplayName": tenantDisplayName,
                "status": status,
                "provisionDate": provisionDate,
                "currentDataVersion": currentDataVersion,
                "dataVersionDate": dataVersionDate,
                "modules": modules,
                "industryCode": industryCode,
                "canAdministerOtherTenants": canAdministerOtherTenants,
                "embeddableDomains": embeddableDomains,
                "customProperties": customProperties,
                "ssoInstanceIssuers": ssoInstanceIssuers,
                "vanityUrlName": vanityUrlName,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenantCode"]) -> MetaOapg.properties.tenantCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenantDisplayName"]) -> MetaOapg.properties.tenantDisplayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provisionDate"]) -> MetaOapg.properties.provisionDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currentDataVersion"]) -> MetaOapg.properties.currentDataVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataVersionDate"]) -> MetaOapg.properties.dataVersionDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modules"]) -> MetaOapg.properties.modules: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["industryCode"]) -> MetaOapg.properties.industryCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canAdministerOtherTenants"]) -> MetaOapg.properties.canAdministerOtherTenants: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embeddableDomains"]) -> 'TenantDetailAPIDTOEmbeddableDomains': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customProperties"]) -> MetaOapg.properties.customProperties: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ssoInstanceIssuers"]) -> 'TenantDetailAPIDTOSsoInstanceIssuers': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vanityUrlName"]) -> MetaOapg.properties.vanityUrlName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tenantCode", "tenantDisplayName", "status", "provisionDate", "currentDataVersion", "dataVersionDate", "modules", "industryCode", "canAdministerOtherTenants", "embeddableDomains", "customProperties", "ssoInstanceIssuers", "vanityUrlName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenantCode"]) -> typing.Union[MetaOapg.properties.tenantCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenantDisplayName"]) -> typing.Union[MetaOapg.properties.tenantDisplayName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provisionDate"]) -> typing.Union[MetaOapg.properties.provisionDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currentDataVersion"]) -> typing.Union[MetaOapg.properties.currentDataVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataVersionDate"]) -> typing.Union[MetaOapg.properties.dataVersionDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modules"]) -> typing.Union[MetaOapg.properties.modules, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["industryCode"]) -> typing.Union[MetaOapg.properties.industryCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canAdministerOtherTenants"]) -> typing.Union[MetaOapg.properties.canAdministerOtherTenants, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embeddableDomains"]) -> typing.Union['TenantDetailAPIDTOEmbeddableDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customProperties"]) -> typing.Union[MetaOapg.properties.customProperties, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ssoInstanceIssuers"]) -> typing.Union['TenantDetailAPIDTOSsoInstanceIssuers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vanityUrlName"]) -> typing.Union[MetaOapg.properties.vanityUrlName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tenantCode", "tenantDisplayName", "status", "provisionDate", "currentDataVersion", "dataVersionDate", "modules", "industryCode", "canAdministerOtherTenants", "embeddableDomains", "customProperties", "ssoInstanceIssuers", "vanityUrlName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tenantCode: typing.Union[MetaOapg.properties.tenantCode, str, schemas.Unset] = schemas.unset,
        tenantDisplayName: typing.Union[MetaOapg.properties.tenantDisplayName, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        provisionDate: typing.Union[MetaOapg.properties.provisionDate, str, schemas.Unset] = schemas.unset,
        currentDataVersion: typing.Union[MetaOapg.properties.currentDataVersion, str, schemas.Unset] = schemas.unset,
        dataVersionDate: typing.Union[MetaOapg.properties.dataVersionDate, str, schemas.Unset] = schemas.unset,
        modules: typing.Union[MetaOapg.properties.modules, list, tuple, schemas.Unset] = schemas.unset,
        industryCode: typing.Union[MetaOapg.properties.industryCode, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        canAdministerOtherTenants: typing.Union[MetaOapg.properties.canAdministerOtherTenants, bool, schemas.Unset] = schemas.unset,
        embeddableDomains: typing.Union['TenantDetailAPIDTOEmbeddableDomains', schemas.Unset] = schemas.unset,
        customProperties: typing.Union[MetaOapg.properties.customProperties, list, tuple, schemas.Unset] = schemas.unset,
        ssoInstanceIssuers: typing.Union['TenantDetailAPIDTOSsoInstanceIssuers', schemas.Unset] = schemas.unset,
        vanityUrlName: typing.Union[MetaOapg.properties.vanityUrlName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TenantDetailAPIDTO':
        return super().__new__(
            cls,
            *args,
            tenantCode=tenantCode,
            tenantDisplayName=tenantDisplayName,
            status=status,
            provisionDate=provisionDate,
            currentDataVersion=currentDataVersion,
            dataVersionDate=dataVersionDate,
            modules=modules,
            industryCode=industryCode,
            canAdministerOtherTenants=canAdministerOtherTenants,
            embeddableDomains=embeddableDomains,
            customProperties=customProperties,
            ssoInstanceIssuers=ssoInstanceIssuers,
            vanityUrlName=vanityUrlName,
            _configuration=_configuration,
            **kwargs,
        )

from visier_tenant_management_python_sdk.model.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.model.tenant_detail_apidto_embeddable_domains import TenantDetailAPIDTOEmbeddableDomains
from visier_tenant_management_python_sdk.model.tenant_detail_apidto_sso_instance_issuers import TenantDetailAPIDTOSsoInstanceIssuers
from visier_tenant_management_python_sdk.model.tenant_module_dto import TenantModuleDTO
