# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_tenant_management_python_sdk.paths.v1_admin_tenants.post import AddTenantRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id.delete import DeleteTenantRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id_disable.put import DisableTenantRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id_enable.put import EnableTenantRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id.get import GetTenantRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants.get import GetTenantsRaw
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id.put import UpdateTenantRaw
from visier_tenant_management_python_sdk.paths.v1_op_validation_tenants_tenant_id.get import ValidateTenantRaw
from visier_tenant_management_python_sdk.paths.v1_op_validation_tenants.get import ValidateTenantsRaw


class TenantManagementV1ApiRaw(
    AddTenantRaw,
    DeleteTenantRaw,
    DisableTenantRaw,
    EnableTenantRaw,
    GetTenantRaw,
    GetTenantsRaw,
    UpdateTenantRaw,
    ValidateTenantRaw,
    ValidateTenantsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
