# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_tenant_management_python_sdk.paths.v2_admin_tenants.post import CreateTenant
from visier_tenant_management_python_sdk.paths.v2_admin_tenants.get import ListTenants
from visier_tenant_management_python_sdk.paths.v2_admin_tenants_tenant_id.get import TenantInfo
from visier_tenant_management_python_sdk.paths.v2_admin_tenants_tenant_id.put import UpdateTenant
from visier_tenant_management_python_sdk.apis.tags.tenant_management_api_raw import TenantManagementApiRaw


class TenantManagementApi(
    CreateTenant,
    ListTenants,
    TenantInfo,
    UpdateTenant,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TenantManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TenantManagementApiRaw(api_client)
