# coding: utf-8
"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_tenant_management_python_sdk.client_custom import ClientCustom
from visier_tenant_management_python_sdk.configuration import Configuration
from visier_tenant_management_python_sdk.api_client import ApiClient
from visier_tenant_management_python_sdk.type_util import copy_signature
from visier_tenant_management_python_sdk.apis.tags.tenant_management_api import TenantManagementApi
from visier_tenant_management_python_sdk.apis.tags.tenant_management_v1_api import TenantManagementV1Api



class VisierTenantManagement(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.tenant_management: TenantManagementApi = TenantManagementApi(api_client)
        self.tenant_management_v1: TenantManagementV1Api = TenantManagementV1Api(api_client)
