# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import visier_tenant_management_python_sdk
from visier_tenant_management_python_sdk.paths.v1_admin_tenants_tenant_id_disable import put
from visier_tenant_management_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1AdminTenantsTenantIdDisable(ApiTestMixin, unittest.TestCase):
    """
    V1AdminTenantsTenantIdDisable unit test stubs
        Disable an analytic tenant
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
