# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHomeAnalysisByUserGroupDTO(TypedDict):
    pass

class OptionalHomeAnalysisByUserGroupDTO(TypedDict, total=False):
    # The user group ID.
    userGroupId: str

    # The unique ID of the analysis to show for this user group when a user logs in.
    homeAnalysisId: str

class HomeAnalysisByUserGroupDTO(RequiredHomeAnalysisByUserGroupDTO, OptionalHomeAnalysisByUserGroupDTO):
    pass
