# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.module_settings_dto import ModuleSettingsDTO

class RequiredTenantModuleDTO(TypedDict):
    pass

class OptionalTenantModuleDTO(TypedDict, total=False):
    # An identifiable name that is displayed within Visier. For example, \"TALENT\".
    displayName: str

    # The symbol name of the module. For example, \"Talent_Management\".
    symbolName: str

    # The settings associated with the module.
    moduleSettings: ModuleSettingsDTO

class TenantModuleDTO(RequiredTenantModuleDTO, OptionalTenantModuleDTO):
    pass
