# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.tenant_management_api_get_response_dto import TenantManagementAPIGetResponseDTO

class RequiredTenantManagementAPIListResponseDTO(TypedDict):
    pass

class OptionalTenantManagementAPIListResponseDTO(TypedDict, total=False):
    # A list of objects representing all the analytic tenants.
    tenants: typing.List[TenantManagementAPIGetResponseDTO]

    # The limit of analytic tenants to return. The maximum value is 1000. The default is 150.
    limit: int

    # The index to start retrieving values from, also known as offset. The index begins at 0.
    start: int

class TenantManagementAPIListResponseDTO(RequiredTenantManagementAPIListResponseDTO, OptionalTenantManagementAPIListResponseDTO):
    pass
