# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.type.tenant_detail_apidto_embeddable_domains import TenantDetailAPIDTOEmbeddableDomains
from visier_tenant_management_python_sdk.type.tenant_detail_apidto_sso_instance_issuers import TenantDetailAPIDTOSsoInstanceIssuers
from visier_tenant_management_python_sdk.type.tenant_module_dto import TenantModuleDTO

class RequiredTenantDetailAPIDTO(TypedDict):
    pass

class OptionalTenantDetailAPIDTO(TypedDict, total=False):
    # The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".
    tenantCode: str

    # An identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
    tenantDisplayName: str

    # Whether the tenant is enabled or disabled.
    status: str

    # The date that the tenant was created.
    provisionDate: str

    # The data version ID that the tenant is using.
    currentDataVersion: str

    # The date that the data version was published to production.
    dataVersionDate: str

    # The modules assigned to the analytic tenant.
    modules: typing.List[TenantModuleDTO]

    # The 6-digit NAICS code for the industry to which the analytic tenant belongs.
    industryCode: int

    # If true, the tenant is an administrating tenant.
    canAdministerOtherTenants: bool

    embeddableDomains: TenantDetailAPIDTOEmbeddableDomains

    # A set of key-value pairs that represent different customizable properties for the analytic tenant.
    customProperties: typing.List[CustomTenantPropertyDTO]

    ssoInstanceIssuers: TenantDetailAPIDTOSsoInstanceIssuers

    # The name of the administrating tenant used in Visier URLs.
    vanityUrlName: str

class TenantDetailAPIDTO(RequiredTenantDetailAPIDTO, OptionalTenantDetailAPIDTO):
    pass
