# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTenantStatusAPIDTO(TypedDict):
    pass

class OptionalTenantStatusAPIDTO(TypedDict, total=False):
    # The unique identifier for the analytic tenant.
    tenantCode: str

    # Whether the tenant is enabled or disabled.
    status: str

    # The identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
    tenantDisplayName: str

    # If true, the tenant is an administrating tenant.
    canAdministerOtherTenants: bool

class TenantStatusAPIDTO(RequiredTenantStatusAPIDTO, OptionalTenantStatusAPIDTO):
    pass
