# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_embeddable_domains import TenantProvisionAPIDTOEmbeddableDomains
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_purchased_modules import TenantProvisionAPIDTOPurchasedModules
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_sso_instance_issuers import TenantProvisionAPIDTOSsoInstanceIssuers

class RequiredTenantProvisionAPIDTO(TypedDict):
    pass

class OptionalTenantProvisionAPIDTO(TypedDict, total=False):
    # The unique identifier of the analytic tenant.
    tenantCode: str

    # The display name that is assigned to the analytic tenant.
    tenantDisplayName: str

    purchasedModules: TenantProvisionAPIDTOPurchasedModules

    # The 6-digit NAICS code for the industry to which the analytic tenant belongs. If the code is unknown, type 000000.   For 2-digit codes, add trailing zeros at the end to reach 6 digits, such as 620000.
    industryCode: int

    embeddableDomains: TenantProvisionAPIDTOEmbeddableDomains

    # A set of key-value pairs that represent different customizable properties for the analytic tenant.
    customProperties: typing.List[CustomTenantPropertyDTO]

    ssoInstanceIssuers: TenantProvisionAPIDTOSsoInstanceIssuers

class TenantProvisionAPIDTO(RequiredTenantProvisionAPIDTO, OptionalTenantProvisionAPIDTO):
    pass
