# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.tenant_preview_entries_summary_dto import TenantPreviewEntriesSummaryDTO

class RequiredTenantPreviewEntriesSummaryListDTO(TypedDict):
    pass

class OptionalTenantPreviewEntriesSummaryListDTO(TypedDict, total=False):
    # A list of objects representing all the analytic tenants.
    tenants: typing.List[TenantPreviewEntriesSummaryDTO]

    # The number of analytic tenants to retrieve. The maximum number to retrieve is 1000.
    limit: int

    # The index to start retrieving results from, also known as offset. The index begins at 0.
    start: int

class TenantPreviewEntriesSummaryListDTO(RequiredTenantPreviewEntriesSummaryListDTO, OptionalTenantPreviewEntriesSummaryListDTO):
    pass
