# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_tenant_management_python_sdk.type.update_tenant_model_custom_properties import UpdateTenantModelCustomProperties
from visier_tenant_management_python_sdk.type.update_tenant_model_embeddable_domains import UpdateTenantModelEmbeddableDomains
from visier_tenant_management_python_sdk.type.update_tenant_model_purchased_modules import UpdateTenantModelPurchasedModules
from visier_tenant_management_python_sdk.type.update_tenant_model_sso_instance_issuers import UpdateTenantModelSsoInstanceIssuers

class RequiredUpdateTenantModel(TypedDict):
    pass

class OptionalUpdateTenantModel(TypedDict, total=False):
    # A display name that is assigned to the new analytic tenant.
    tenantDisplayName: str

    # The 6-digit NAICS code for the industry to which the analytic tenant belongs. If the code is unknown, type 000000.   For 2-digit codes, add trailing zeros at the end to reach 6 digits, such as 620000.
    industryCode: int

    purchasedModules: UpdateTenantModelPurchasedModules

    embeddableDomains: UpdateTenantModelEmbeddableDomains

    customProperties: UpdateTenantModelCustomProperties

    ssoInstanceIssuers: UpdateTenantModelSsoInstanceIssuers

class UpdateTenantModel(RequiredUpdateTenantModel, OptionalUpdateTenantModel):
    pass
