# coding: utf-8

"""
    Visier Tenant Management APIs

    Visier APIs for managing tenants

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from visier_tenant_management_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from visier_tenant_management_python_sdk.api_response import AsyncGeneratorResponse
from visier_tenant_management_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_tenant_management_python_sdk import schemas  # noqa: F401

from visier_tenant_management_python_sdk.model.custom_tenant_property_dto import CustomTenantPropertyDTO as CustomTenantPropertyDTOSchema
from visier_tenant_management_python_sdk.model.tenant_provision_apidto import TenantProvisionAPIDTO as TenantProvisionAPIDTOSchema
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_embeddable_domains import TenantProvisionAPIDTOEmbeddableDomains as TenantProvisionAPIDTOEmbeddableDomainsSchema
from visier_tenant_management_python_sdk.model.status import Status as StatusSchema
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_sso_instance_issuers import TenantProvisionAPIDTOSsoInstanceIssuers as TenantProvisionAPIDTOSsoInstanceIssuersSchema
from visier_tenant_management_python_sdk.model.tenant_provision_apidto_purchased_modules import TenantProvisionAPIDTOPurchasedModules as TenantProvisionAPIDTOPurchasedModulesSchema

from visier_tenant_management_python_sdk.type.status import Status
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_sso_instance_issuers import TenantProvisionAPIDTOSsoInstanceIssuers
from visier_tenant_management_python_sdk.type.tenant_provision_apidto import TenantProvisionAPIDTO
from visier_tenant_management_python_sdk.type.custom_tenant_property_dto import CustomTenantPropertyDTO
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_purchased_modules import TenantProvisionAPIDTOPurchasedModules
from visier_tenant_management_python_sdk.type.tenant_provision_apidto_embeddable_domains import TenantProvisionAPIDTOEmbeddableDomains

from ...api_client import Dictionary
from visier_tenant_management_python_sdk.pydantic.tenant_provision_apidto_purchased_modules import TenantProvisionAPIDTOPurchasedModules as TenantProvisionAPIDTOPurchasedModulesPydantic
from visier_tenant_management_python_sdk.pydantic.tenant_provision_apidto import TenantProvisionAPIDTO as TenantProvisionAPIDTOPydantic
from visier_tenant_management_python_sdk.pydantic.tenant_provision_apidto_sso_instance_issuers import TenantProvisionAPIDTOSsoInstanceIssuers as TenantProvisionAPIDTOSsoInstanceIssuersPydantic
from visier_tenant_management_python_sdk.pydantic.custom_tenant_property_dto import CustomTenantPropertyDTO as CustomTenantPropertyDTOPydantic
from visier_tenant_management_python_sdk.pydantic.tenant_provision_apidto_embeddable_domains import TenantProvisionAPIDTOEmbeddableDomains as TenantProvisionAPIDTOEmbeddableDomainsPydantic
from visier_tenant_management_python_sdk.pydantic.status import Status as StatusPydantic

# body param
SchemaForRequestBodyApplicationJson = TenantProvisionAPIDTOSchema


request_body_tenant_provision_apidto = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = TenantProvisionAPIDTOSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: TenantProvisionAPIDTO


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: TenantProvisionAPIDTO


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = StatusSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: Status


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: Status


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _add_tenant_mapped_args(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if tenant_code is not None:
            _body["tenantCode"] = tenant_code
        if tenant_display_name is not None:
            _body["tenantDisplayName"] = tenant_display_name
        if purchased_modules is not None:
            _body["purchasedModules"] = purchased_modules
        if industry_code is not None:
            _body["industryCode"] = industry_code
        if embeddable_domains is not None:
            _body["embeddableDomains"] = embeddable_domains
        if custom_properties is not None:
            _body["customProperties"] = custom_properties
        if sso_instance_issuers is not None:
            _body["ssoInstanceIssuers"] = sso_instance_issuers
        args.body = _body
        return args

    async def _aadd_tenant_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Add an analytic tenant
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/admin/tenants',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_tenant_provision_apidto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _add_tenant_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Add an analytic tenant
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/admin/tenants',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_tenant_provision_apidto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class AddTenantRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aadd_tenant(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_tenant_mapped_args(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
        )
        return await self._aadd_tenant_oapg(
            body=args.body,
            **kwargs,
        )
    
    def add_tenant(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_tenant_mapped_args(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
        )
        return self._add_tenant_oapg(
            body=args.body,
        )

class AddTenant(BaseApi):

    async def aadd_tenant(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
        validate: bool = False,
        **kwargs,
    ) -> TenantProvisionAPIDTOPydantic:
        raw_response = await self.raw.aadd_tenant(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
            **kwargs,
        )
        if validate:
            return TenantProvisionAPIDTOPydantic(**raw_response.body)
        return api_client.construct_model_instance(TenantProvisionAPIDTOPydantic, raw_response.body)
    
    
    def add_tenant(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
        validate: bool = False,
    ) -> TenantProvisionAPIDTOPydantic:
        raw_response = self.raw.add_tenant(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
        )
        if validate:
            return TenantProvisionAPIDTOPydantic(**raw_response.body)
        return api_client.construct_model_instance(TenantProvisionAPIDTOPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_tenant_mapped_args(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
        )
        return await self._aadd_tenant_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        tenant_code: typing.Optional[str] = None,
        tenant_display_name: typing.Optional[str] = None,
        purchased_modules: typing.Optional[TenantProvisionAPIDTOPurchasedModules] = None,
        industry_code: typing.Optional[int] = None,
        embeddable_domains: typing.Optional[TenantProvisionAPIDTOEmbeddableDomains] = None,
        custom_properties: typing.Optional[typing.List[CustomTenantPropertyDTO]] = None,
        sso_instance_issuers: typing.Optional[TenantProvisionAPIDTOSsoInstanceIssuers] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_tenant_mapped_args(
            tenant_code=tenant_code,
            tenant_display_name=tenant_display_name,
            purchased_modules=purchased_modules,
            industry_code=industry_code,
            embeddable_domains=embeddable_domains,
            custom_properties=custom_properties,
            sso_instance_issuers=sso_instance_issuers,
        )
        return self._add_tenant_oapg(
            body=args.body,
        )

